In [1]:
import numpy as np
import pandas as pd

In [4]:
number = [0,1,2,3,4,5,6,7,8,9]

In [9]:
letter = ['a', 'b', 'c','d','d','f','g','h','i','j']
 

In [8]:
string = 'a'


In [17]:
dic = {
    'number': number,
    'letter': letter
}
dataframe = pd.DataFrame(dic)
print(dataframe)


   number letter
0       0      a
1       1      b
2       2      c
3       3      d
4       4      d
5       5      f
6       6      g
7       7      h
8       8      i
9       9      j


In [19]:
dataframe['letter']

0    a
1    b
2    c
3    d
4    d
5    f
6    g
7    h
8    i
9    j
Name: letter, dtype: object

In [20]:
dataframe.to_numpy

<bound method DataFrame.to_numpy of    number letter
0       0      a
1       1      b
2       2      c
3       3      d
4       4      d
5       5      f
6       6      g
7       7      h
8       8      i
9       9      j>

In [22]:
dataframe.values

array([[0, 'a'],
       [1, 'b'],
       [2, 'c'],
       [3, 'd'],
       [4, 'd'],
       [5, 'f'],
       [6, 'g'],
       [7, 'h'],
       [8, 'i'],
       [9, 'j']], dtype=object)

In [26]:
x = np.arange(0,4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [32]:
x = []
x = np.append(0, 1)
fo
x

array([1, 1])

In [35]:

x = [ [1,2],[3,4] ]
x = np.array(x)
x.shape




(2, 2)

In [41]:
a = [2,3]
a = np.array(a)
a.shape
a * x

array([[ 2,  6],
       [ 6, 12]])

In [45]:
a = [2, 2]
a = np.array(a)

b = [4, 5]
b = np.array(b)

c = np.dot(a,b)
c

18

In [47]:
import requests
from bs4 import BeautifulSoup


In [58]:
url = requests.get("https://www.imdb.com/search/title/?title_type=feature&num_votes=25000,&genres=sci-fi&sort=user_rating,desc&start=51&ref_=adv_nxt"
)
soup = BeautifulSoup(url.content, 'html.parser')