In [3]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [13]:
array1 = np.arange(12).reshape(3, 4)
print(array1)
array1[[0, 1],:] = array1[[1, 0],:]
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]


**75. How to compute averages using a sliding window over an array?**

In [23]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

a = np.arange(20)
moving_average(a,6)


array([ 2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5,
       13.5, 14.5, 15.5, 16.5])